version: 2.1
jobs:
  build:
    working_directory: /go/src/github.com/xAbdullahShaikh/DevOps_Assignement_2
    docker:
      - image: circleci/golang:1.21
    branches:
      only:
        - master
    steps:
      - checkout
      - run:
          name: Enable Go Modules
          command: |
            export GO111MODULE=on
            go mod init || true
            go mod tidy
      - run:
          name: Build Application
          command: go build -o invoicer ./...
      - run:
          name: Run Tests
          command: go test ./...
      - setup_remote_docker
      - run:
          name: Build and Push Docker Image
          command: |
            docker build -t abdullahshaikh/invoicer .
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
              docker push abdullahshaikh/invoicer
            fi
