version: 2
jobs:
  build:
    working_directory: /go/src/github.com/Securing-DevOps/invoicer
    docker:
      - image: circleci/golang:1.11
    branches:
      only:
        - master
    steps:
      - checkout
      - setup_remote_docker

      - run: echo 'export GOPATH_HEAD="$(echo ${GOPATH}|cut -d ':' -f 1)"' >> $BASH_ENV
      - run: echo 'export GOPATH_BASE="${GOPATH_HEAD}/src/github.com/${CIRCLE_PROJECT_USERNAME}"' >> $BASH_ENV
      - run: echo 'export DOCKER_REPO="codenameab/devsecops_2"' >> $BASH_ENV
      - run: mkdir -p "${GOPATH_BASE}"
      - run: mkdir -p "${GOPATH_HEAD}/bin"
      - run: go get github.com/govend/govend

      - run:
          name: Build application container
          command: |
            go install --ldflags '-extldflags "-static"' github.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME};
            [ ! -e bin ] && mkdir bin;
            cp "${GOPATH_HEAD}/bin/${CIRCLE_PROJECT_REPONAME}" bin/invoicer;
            docker build -t codenameab/devsecops_2 .;

      - run:
          name: Run application in background
          command: |
            docker run codenameab/devsecops_2
          background: true

      - run:
          name: ZAP baseline test of application
          command: |
            (
            docker pull owasp/zap2docker-weekly && \
            docker run -t owasp/zap2docker-weekly zap-baseline.py \
                -u https://raw.githubusercontent.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/master/zap-baseline.conf \
                -t http://172.17.0.2:8080/ || \
            if [ $? -ne 1 ]; then exit 0; else exit 1; fi;
            )

      - run:
          name: Test dependencies are up to date
          command: 'GOPATH="${GOPATH_HEAD}"; ( cd ${GOPATH_BASE}/${CIRCLE_PROJECT_REPONAME} && govend -u --prune && git diff --quiet )'

      - deploy:
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
                docker login -u codenameab -p ${DOCKER_PASSWORD};
                docker push codenameab/devsecops_2;
            fi
